### PR TITLE
fixed list structure from 6. onwards

### PR DESCRIPTION
**Pull request by tosteiner**
@Protohedgehog could you initiate a site rebuild after merging this? should fix the inconsistent TOC listing from Point 6 onwards...

### CODE REVIEW

**Comment by Protohedgehog** [comment]
Awesome, thanks! The site should automatically rebuild as changes are pushed through too :)

**Comment by cMadan** [comment]
Thanks for fixing this! Was bugging me a bit that the TOC changes I made conflicted with other changes that you had been making concurrently.

**Comment by Protohedgehog** [comment]
Is that a pun @cMadan? ;)

**Comment by cMadan** [comment]
No...? Or, at least I don't get it :P

**Comment by Protohedgehog** [comment]
Bugging.. Fixing bugs.. Oh never mind.. XD

**Comment by tosteiner** [comment]
now it should be consistent throughout :)

**Comment by cMadan** [comment]
@Protohedgehog, that's just how I talk :P. So, I'm not sure if you're over- or under-estimating my wit here :).

**Pull request merged**
